### ISSUE TITLE
Request for SQL examples

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb-docs#67]
Dear Developers,

could you please add examples in the documentation for:

* [ ] `CREATE PROPERTY` with a `MAP` and `LIST` data-type including a type definition of the contained type (unfortunately, mine only work for `EMBEDDED`)
* [x] `INSERT INTO` for a `MAP` and `LIST` Property.

Thank you very much

**Comment by gramian** [comment]
@lvca If you provide an example here on how to use `CREATE PROPERTY` for a `LIST`, I could add it to the documentation. Relatedly: do lists have an (optional) type like `MAP`?

**Comment by gramian** [comment]
So, I guess as this list-with-member-type command errors:
```
CREATE PROPERTY MyType.ListProperty LIST STRING
```
I should file a bug?

**Comment by lvca** [comment]
Interesting issue this: the linked type is supported by the grammar because inherited from OrientDB. But the linked type is never used. It could be nice having it as a constraint. For example, you can define `LIST STRING` (as from your example) and ArcadeDB could check that only strings are inside the list.

Even if it's nice to have it in terms of validation, it adds overhead because every time a property declares a linked type, all its content must be browsed and checked to save time. But this would be still optional, if you declare it, it will take down performance on save, "performance discretion advised".

Any opinions?

**Comment by gramian** [comment]
IMHO: I am fine either way, but it should be consistent with the `MAP` container, which apparently correctly supports value type constraints. However, I would have a use-case for typed containers. Having said that, I would also consider how complex/robust the associated engine code is. Maybe it is worth getting rid of a lot/fragile code?

**Comment by lvca** [comment]
+1. Removed from the grammar and code.

**Comment by gramian** [comment]
I found no more references in the docu to typed containers, so I guess this issue can be closed?

**Comment by lvca** [comment]
Great, thanks @gramian
