### ISSUE TITLE
Details on fields returned by `CHECK DATABASE`

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb-docs#88]
Dear Developers,

the `CHECK DATABASE` command returns various fields:
```
avgPageUsed,
warnings,
totalSurrogateRecords,
pageSize,
totalDeletedRecords,
totalAllocatedRecords,
totalActiveRecords,
totalActiveEdges,
totalMaxOffset,
totalAllocatedVertices,
deletedRecords,
corruptedRecords,
totalPages,
totalPlaceholderRecords,
rebuiltIndexes,
totalAllocatedEdges,
operation,
invalidLinks,
errors,
autoFix,
totalActiveVertices
```
whose meaning is not immediately clear. Hence, I suggest to add a table to the docs explaining them. Questions about these fields that come to mind are:
* What is a "page"?
* Why are `warnings` an array, while `errors` are an integer (count)?
* What is the unit of `pageSize`? ie Bytes
* What does "active" mean?
* What does `totalMaxOffset` mean?
* What does `autoFix` mean? ie "fixed" or "fixable"
* Can `operation` be anything but `check database`?

On a side note: the result of `CHECK DATABASE` does not seem to be a regular query result, as it cannot be reused as a sub query, ie `SELECT errors FROM (CHECK DATABASE);`

PS: I can help adding this info if it is provided.

**Comment by lvca** [comment]
Good point. Trying to explain things here:

`avgPageUsed` is the average space used in pages. It's a percentage value. 100% means all the pages are full. It's something useful to understand if the records are too big and split into multiple pages. Sometimes helps create buckets with larger pages to accommodate large records. If a record doesn't fit a page is split into multiple pages and multiple reads are necessary.

`warnings` is a set of warning messages

`totalSurrogateRecords ` is quite internal but means the number of records that have been moved between pages. This happens when a record is updated and doesn't fit the original page, so a surrogate (placeholder) is set to point to the new page/position or it's a piece of a record stored on multiple pages. You can ignore this.

`totalPlaceholderRecords` similar to above, you can ignore this.

`pageSize` can be ignored

`totalDeletedRecords`  number of records deleted in the database. When a record is deleted, it's RID is not recycled

`totalAllocatedRecords` is the total number of records created in the database. Any type of records, documents, vertices and edges.

`totalAllocatedVertices` like above but only for vertices

`totalAllocatedVertices` like above but only for edges

`totalActiveRecords` is the total number of records that are "active" = not deleted. Any type of records, documents, vertices and edges.

`totalActiveVertices` like above, but for vertices only

`totalActiveEdges` like above, but for edges only

'totalMaxOffset' is internal, you can ignore it

`deletedRecords` total records deleted in the database (allocated - active)

`corruptedRecords` are all the records not found in the database. This could happen with broken edges (edges pointing to deleted vertices). This should be zero, if not means there is a bug in the graph operations that doesn't keep operations 100% transactional

`totalPages` total number of pages in the database

`rebuiltIndexes` is the list of indexes that have been rebuilt automatically if corrupted records were found

`operation` you can ignore it, it's set by the console

`invalidLinks` similar to corrupted records. it should be zero.

`errors` is a counter of errors encountered while checking the database. it should be zero, of course.

`autoFix` is a counter of autofix operation executed by the check database under the hood when corrupted records have been encountered. Some operations, like broken edges, can be fixed and restored automatically.

**Comment by lvca** [comment]
@gramian if you feel like creating a table in the docs, I'd be happy to merge it :-)

**Comment by gramian** [comment]
On `deletedRecords`: it is of type list, so it probably is supposed to hold the deleted record or maybe its RID(?). However deleting a record increments `totalDeletedRecords` as expected, but `deletedRecords` remains empty.

**Comment by lvca** [comment]
`deletedRecords` has the list of RID deleted after a fix. The fix, in this case, is when a corrupted record is found. This was more relevant at the beginning of the development of the storage. Probably the name should be something like "deletedRecordsAfterFix". I should rename it.

**Comment by lvca** [comment]
Ok, renamed

**Comment by gramian** [comment]
@lvca What about `errors` and `totalAllocatedDocuments`, see [above](https://github.com/ArcadeData/arcadedb-docs/issues/88#issuecomment-1338073497).

**Comment by lvca** [comment]
100% agree. Fixed
